name: Deploy Branch to Pantheon Multidev
on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: Get Committer Email and Name
      run: |
          COMMITTER_EMAIL=$(git log --format='%ae' -n 1 ${{ github.sha }})
          COMMITTER_NAME=$(git log --format='%an' -n 1 ${{ github.sha }})

          # Configure git defaults
          git config --global user.email "$COMMITTER_EMAIL"
          git config --global user.name "$COMMITTER_NAME"
    - name: Sync code to site
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        # Setup remote branch connection
        PR_BRANCH_NAME=${GITHUB_REF##*/}
        echo "PR_BRANCH_NAME=$PR_BRANCH_NAME" >> $GITHUB_ENV
        git remote add pantheon $pantheon_repo

        # Set to git mode
        if terminus env:info $pantheon_site_name.$PR_BRANCH_NAME > /dev/null 2>&1; then
          terminus connection:set$pantheon_site_name.$PR_BRANCH_NAME git
        fi

        # Fetch full history from pantheon
        # git fetch --unshallow pantheon
        #git checkout -b $PR_BRANCH_NAME
        #git add .

        # Sync branch
        # git commit -m "GHA Upstream PR"
        git push -u --force pantheon HEAD:refs/heads/$PR_BRANCH_NAME
    - name: Create multidev if needed
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        if ! terminus env:info $pantheon_site_name.$PR_BRANCH_NAME > /dev/null 2>&1; then
            terminus env:create $pantheon_site_name.live $PR_BRANCH_NAME
        else
            echo "Environment $PR_BRANCH_NAME already exists."
        fi
        MULTIDEV_URL=$(echo "https://$PR_BRANCH_NAME-$pantheon_site_name.pantheonsite.io")
        echo "MULTIDEV_URL=$MULTIDEV_URL" >> "$GITHUB_ENV"
    - name: Add deploy URL to PR description
      if: github.event_name == 'pull_request'
      uses: chabroA/action-append-pr-description@master
      with:
        auth: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}
        pr: ${{ github.event.number }}
        url: ${{ env.MULTIDEV_URL }}
        message: "Deployment URL: "

  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@master
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://nammweb.atlassian.net/
          skip-branches: '^(production-release|main|master|release\/v\d+)$' #optional 
          custom-issue-number-regexp: '^\d+' #optional
          jira-project-key: 'NWR' #optional