name: Deploy Branch to Pantheon Multidev
on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        git remote add pantheon $pantheon_repo
        git push -u pantheon HEAD:refs/heads/$BASE_BRANCH
        if ! terminus env:info $pantheon_site_name.$BASE_BRANCH > /dev/null 2>&1; then
            terminus multidev:create $pantheon_site_name.live $BASE_BRANCH
        else
            echo "Environment $BASE_BRANCH already exists."
        fi
        MULTIDEV_URL="https://$BASE_BRANCH-$pantheon_site_name.pantheonsite.io"
        echo "MULTIDEV_URL=$MULTIDEV_URL" >> $GITHUB_ENV
        echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
        echo "PANTHEON_SITE_NAME=$pantheon_site_name" >> $GITHUB_ENV
    - name: Add deploy URL to PR description
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const MULTIDEV_URL = process.env.MULTIDEV_URL;
          const BASE_BRANCH = process.env.BASE_BRANCH;
          const PANTHEON_SITE_NAME = process.env.PANTHEON_SITE_NAME;
          const doubleDash = (str) => str.replace(/-/g, '--');
          const site = doubleDash(PANTHEON_SITE_NAME);
          const branch = doubleDash(BASE_BRANCH);
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `[![Static Badge](https://img.shields.io/badge/${site}-${branch}-%23FFDC28?logo=pantheon&logoColor=white)](${MULTIDEV_URL})`
          });
