name: Deploy Branch to Pantheon Multidev
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: Validate and rename branch if necessary
      id: rename_branch
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        VALID_BRANCH=$(echo "$BASE_BRANCH" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]' | cut -c1-10)
        if [ "$BASE_BRANCH" != "$VALID_BRANCH" ]; then
          git branch -m $BASE_BRANCH $VALID_BRANCH
          git push origin :$BASE_BRANCH
          git push origin $VALID_BRANCH
        fi
        echo "::set-output name=branch::${VALID_BRANCH:-$BASE_BRANCH}"
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
        BASE_BRANCH: ${{ steps.rename_branch.outputs.branch }}
      run: |
        git remote add pantheon $pantheon_repo
        git push -u pantheon HEAD:refs/heads/$BASE_BRANCH
        terminus multidev:create $pantheon_site_name.live $BASE_BRANCH
