name: Deploy Branch to Pantheon Multidev

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Installing Terminus
        uses: kopepasah/setup-pantheon-terminus@master
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: deployer
        env:
          pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
        run: |
          BASE_BRANCH=${GITHUB_REF##*/}
          SHORT_BRANCH=$(echo "$BASE_BRANCH" | sed -E 's/.*(NWR-[0-9]+).*/\1/' | tr '[:upper:]' '[:lower:]')
          git remote add pantheon $pantheon_repo

          # Set to git mode
          if terminus env:info $pantheon_site_name.$SHORT_BRANCH > /dev/null 2>&1; then
            terminus connection:set $pantheon_site_name.$SHORT_BRANCH git
          fi

          git push -u pantheon HEAD:refs/heads/$SHORT_BRANCH

          # Check if the multidev environment already exists
          if ! terminus env:info $pantheon_site_name.$SHORT_BRANCH > /dev/null 2>&1; then
            terminus multidev:create $pantheon_site_name.live $SHORT_BRANCH
          else
            echo "Environment $SHORT_BRANCH already exists."
          fi

          MULTIDEV_URL="https://$SHORT_BRANCH-$pantheon_site_name.pantheonsite.io"
          echo "MULTIDEV_URL=$MULTIDEV_URL" >> $GITHUB_ENV
