name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print PR title and description for debugging
        run: |
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Description: ${{ github.event.pull_request.body }}"

      - uses: cakeinpanic/jira-description-action@master
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://nammweb.atlassian.net/
          skip-branches: '^(production-release|main|master|release\/v\d+)$' #optional 
          jira-project-key: 'NWR'
          custom-issue-number-regexp: 'NWR-\d+'
