name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print PR title and description for debugging
        run: |
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Description: ${{ github.event.pull_request.body }}"

      - uses: cakeinpanic/jira-description-action@master
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://nammweb.atlassian.net/
          skip-branches: '^(production-release|main|master|release\/v\d+)$' #optional 
          jira-project-key: 'NWR'
          custom-issue-number-regexp: '^\d+'

      - name: Additional debug
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}"
          echo "JIRA_BASE_URL: https://nammweb.atlassian.net/"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Body: ${{ github.event.pull_request.body }}"
          curl -H "Authorization: Bearer ${{ secrets.JIRA_TOKEN }}" \
               -H "Content-Type: application/json" \
               "https://nammweb.atlassian.net/rest/api/3/issue/NWR-45"
