name: Add Deploy URL to PR Description

on:
  pull_request:
    types: [opened, edited]
jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          BASE_BRANCH=${GITHUB_HEAD_REF##*/}
          MULTIDEV_URL="https://$BASE_BRANCH-namm-mp-1.pantheonsite.io"
          echo "MULTIDEV_URL=$MULTIDEV_URL" >> $GITHUB_ENV

      - name: Add deploy URL to PR description
        uses: chabroA/action-append-pr-description@master
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          pr: ${{ github.event.pull_request.number }}
          message: "My url: ${{ env.MULTIDEV_URL }}"
