name: Add Deploy URL to PR Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set environment variables
        run: |
          BASE_BRANCH=${GITHUB_HEAD_REF##*/}
          SHORT_BRANCH=$(echo "$BASE_BRANCH" | sed -E 's/.*(NWR-[0-9]+).*/\1/' | tr '[:upper:]' '[:lower:]')
          MULTIDEV_URL="https://$SHORT_BRANCH-namm-mp-1.pantheonsite.io"
          echo "MULTIDEV_URL=$MULTIDEV_URL" >> $GITHUB_ENV

      - name: Add deploy URL to PR description
        uses: chabroA/action-append-pr-description@master
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          pr: ${{ github.event.pull_request.number }}
          url: ${{ env.MULTIDEV_URL }}
          message: "My url: "
