name: Add Deploy URL to PR Description

on:
  pull_request:
    branches:
      - '*'
      - '!main'

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        env:
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
        run: |
          BASE_BRANCH=${GITHUB_HEAD_REF##*/}
          MULTIDEV_URL="https://$BASE_BRANCH-$pantheon_site_name.pantheonsite.io"
          echo "MULTIDEV_URL=$MULTIDEV_URL" >> $GITHUB_ENV
      - name: Add deploy URL to PR description
        uses: chabroA/action-append-pr-description@master
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository.name }}
          owner: ${{ github.repository_owner }}
          pr: ${{ github.event.pull_request.number }}
          url: ${{ env.MULTIDEV_URL }}
          message: "My url: "
